export const ROUTES = {
    DEFAULT: "/",
    SEND: "/send",
    SWAP: "/swap",
    WALLET: "/wallet",
    HISTORY_P : "/history",
    SETTINGS: "/setting",
    PVT_KEY: "/private-key",
    NATIVE_TXN: "/native-tx",
    SET_PASS: "/set-password",
    APPROVE_TXN: "/approve-tx",
    SWAP_APPROVE: "/swap-approve",
    ENTER_PASS: "/enter-password",
    BEFORE_BEGIN: "/before-begin",
    CREATE_WALLET:"/create-wallet",
    LOGIN_APPROVE: "/login-approve",
    IMPORT_WALLET: "/import-wallet",
    MANAGE_WALLET: "/manage-wallet",
    UNLOACK_WALLET: "/unlock-wallet",
    NEW_WALLET_DETAILS: "/new-wallet-details",
    MYACCOUNT:"/my-account",
}